#!/bin/sh

NAME=dockerd
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
DAEMON_ARGS="--max-concurrent-downloads 3 --max-concurrent-uploads 5"
#--cpu-rt-period 100000 --cpu-rt-runtime 95000"

[ -r /etc/default/$NAME ] && . /etc/default/$NAME $1

do_start() {
        echo -n "Starting $NAME: "
        start-stop-daemon --start --quiet --background --make-pidfile \
		--pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS \
                && echo "OK" || echo "FAIL"
}

do_stop() {
        echo -n "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                sleep 1
                do_start
                ;;
	*)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
