---
  os-name: "ReswarmOS"
  version: 0.3.7
  # general board description
  board: raspberrypi
  # specific board model
  model: raspberrypi
  # custom configuration file
  config: config
  # name of image configuration file
  image: genimage-raspberrypi4.cfg
  # reagent
  reagent:
    include: true
    url-latest: https://storage.googleapis.com/re-agent/reagent-latest
    url:
      amd64: https://storage.googleapis.com/re-agent/linux/amd64/0.6.2.5/reagent
      arm64: https://storage.googleapis.com/re-agent/linux/arm64/0.6.2.5/reagent
      armv7: https://storage.googleapis.com/re-agent/linux/armv7/0.6.2.5/reagent
...
