---
  os-name: "ReswarmOS"
  version: 0.2.0
  # general board description
  board: raspberrypi
  # specific board model
  model: raspberrypi4
  # custom configuration file
  config: config
  # name of image configuration file
  image: genimage-raspberrypi4.cfg
  # reagent
  reagent:
    include: true
    url-latest: https://storage.googleapis.com/re-agent/reagent-latest
...
