---
  os-name: "ReswarmOS"
  version: 0.0.1
  codename: "Average Ant"
  # choose a model from {
  #   - raspberry-pi-zero
  #   - raspberry-pi-1,...
  #   - raspberry-pi-4
  #   - all 
  # }
  model: raspberry-pi-4
  config: config_v0.1 
  root-user:
    user: revenant
    password: return
  hostname:
    reckless-reindeer
...
