#!/bin/sh

# source the configuration parser
. /usr/bin/read-ini.sh

# define filename/path of device configuration
CNFG="/boot/device-config.ini"
WCFG="/etc/wpa_supplicant"

if [ ! -f ${CNFG} ]; then
  echo "device configuration file ${CNFG} is missing" >&2
  exit 1
fi

# extract [wifi] section and access credentials device configuration
ssid=$(readini ${CNFG} wifi SSID)
passwd=$(readini ${CNFG} wifi PASSWD)

# define wpa_supplicant.conf with given credentials
wpaconf=$(cat << EOF
ctrl_interface=/var/run/wpa_supplicant
ap_scan=1

network={
  ssid="${ssid}"
  psk="${passwd}"
}
EOF
)

# define name of initial WiFi configuration file
CFGFILE="wifinetwork.conf"

case "$1" in

  start)

    echo "setting up wpa_supplicant.conf for immediate network access..."

    echo "writing to ${WCFG}/${CFGFILE}"
    echo "${wpaconf}" > ${WCFG}/${CFGFILE}

    # adjust soft link to WiFi config
    rm -f /etc/wpa_supplicant.conf
    ln -s ${WCFG}/${CFGFILE} /etc/wpa_supplicant.conf

    # remove this startup configuration script
    rm -vf $0
    ;;

  *)

    echo "Usage: $0 start"
    exit 1
    ;;

esac
