#!/bin/bash
# generated by 'boot/prepare_bootconfig.py'

source log/logging.sh

logging_message "download firmware"

# download firmware
git clone --depth=1 --branch=master https://github.com/raspberrypi/firmware.git /home/mario/ReswarmOS/firmware

logging_message "copy firmware to build directory"

# copy firmware BLOBs
cp -r /home/mario/ReswarmOS/firmware/boot /home/mario/ReswarmOS/boot

