---
  os-name: "ReswarmOS"
  version: 0.1
  codename: "Average Ant"
  architecture: x86_64
  # choose a model from { raspberry-pi-zero,raspberry-pi-1,...,raspberry-pi-4,all}
  model: all
  kernel: 5.8.1 # latest
  partitions:
    - {name: "boot", fstype: fat32, size: 64MiB, label: "boot"}
    # TODO auto-adjust to size of root build folder to make it as small as possible
    - {name: "ReswarmOS", fstype: ext4, size: 50MiB, label: "root"}
    - {name: "share", fstype: ext4, size: 0MiB, label: "none"}
  alignment-offset: 4MiB
  root-user:
    user: revenant
    password: return
  hostname:
    reckless-reindeer
  build:
    binutils: 2.34
    gcc: 10.2.0
    gblic: 2.31
    gmp: latest
    mpfr: latest
    mpc: latest
  packages:
    - {name: bash, version: latest, web: https://www.gnu.org/software/bash/, url: https://ftp.halifax.rwth-aachen.de/gnu/bash/bash-5.1-beta.tar.gz}
    - {name: acl, version: latest, url: http://download.savannah.gnu.org/releases/acl/acl-2.2.53.tar.gz}
    - {name: attr, version: latest, url: http://download.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz}
    - {name: autoconf, version: latest, url: http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz}
    - {name: automake, version: latest, url: http://ftp.gnu.org/gnu/automake/automake-1.16.1.tar.xz}
    - {name: bash, version: latest, url: http://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz}
    - {name: bc, version: latest, url: https://github.com/gavinhoward/bc/archive/2.5.3/bc-2.5.3.tar.gz}
    - {name: binutils, version: latest, url: http://ftp.gnu.org/gnu/binutils/binutils-2.34.tar.xz}
    - {name: bison, version: latest, url: http://ftp.gnu.org/gnu/bison/bison-3.5.2.tar.xz}
    - {name: bzip2, version: latest, url: https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz}
    - {name: check, version: latest, url: https://github.com/libcheck/check/releases/download/0.14.0/check-0.14.0.tar.gz}
    - {name: coreutils, version: latest, url: http://ftp.gnu.org/gnu/coreutils/coreutils-8.31.tar.xz}
    - {name: dbus, version: latest, url: https://dbus.freedesktop.org/releases/dbus/dbus-1.12.16.tar.gz}
    - {name: dejagnu, version: latest, url: http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.2.tar.gz}
    - {name: diffutils, version: latest, url: http://ftp.gnu.org/gnu/diffutils/diffutils-3.7.tar.xz}
    - {name: e2fsprogs, version: latest, url: https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.45.5/e2fsprogs-1.45.5.tar.gz}
    - {name: elfutils, version: latest, url: https://sourceware.org/ftp/elfutils/0.178/elfutils-0.178.tar.bz2}
    - {name: eudev, version: latest, url: https://dev.gentoo.org/~blueness/eudev/eudev-3.2.9.tar.gz}
    - {name: expat, version: latest, url: https://prdownloads.sourceforge.net/expat/expat-2.2.9.tar.xz}
    - {name: expect5.45.4.tar.gz, version: latest, url: https://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz}
    - {name: file, version: latest, url: ftp://ftp.astron.com/pub/file/file-5.38.tar.gz}
    - {name: findutils, version: latest, url: http://ftp.gnu.org/gnu/findutils/findutils-4.7.0.tar.xz}
    - {name: flex, version: latest, url: https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz}
    - {name: gawk, version: latest, url: http://ftp.gnu.org/gnu/gawk/gawk-5.0.1.tar.xz}
    - {name: gcc, version: latest, url: http://ftp.gnu.org/gnu/gcc/gcc-9.2.0/gcc-9.2.0.tar.xz}
    - {name: gdbm, version: latest, url: http://ftp.gnu.org/gnu/gdbm/gdbm-1.18.1.tar.gz}
    - {name: gettext, version: latest, url: http://ftp.gnu.org/gnu/gettext/gettext-0.20.1.tar.xz}
    - {name: glibc, version: latest, url: http://ftp.gnu.org/gnu/glibc/glibc-2.31.tar.xz}
    - {name: gmp, version: latest, url: http://ftp.gnu.org/gnu/gmp/gmp-6.2.0.tar.xz}
    - {name: gperf, version: latest, url: http://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz}
    - {name: grep, version: latest, url: http://ftp.gnu.org/gnu/grep/grep-3.4.tar.xz}
    - {name: groff, version: latest, url: http://ftp.gnu.org/gnu/groff/groff-1.22.4.tar.gz}
    - {name: grub, version: latest, url: https://ftp.gnu.org/gnu/grub/grub-2.04.tar.xz}
    - {name: gzip, version: latest, url: http://ftp.gnu.org/gnu/gzip/gzip-1.10.tar.xz}
    - {name: iana, version: latest, url: http://anduin.linuxfromscratch.org/LFS/iana-etc-2.30.tar.bz2}
    - {name: inetutils, version: latest, url: http://ftp.gnu.org/gnu/inetutils/inetutils-1.9.4.tar.xz}
    - {name: intltool, version: latest, url: https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz}
    - {name: iproute2, version: latest, url: https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-5.5.0.tar.xz}
    - {name: kbd, version: latest, url: https://www.kernel.org/pub/linux/utils/kbd/kbd-2.2.0.tar.xz}
    - {name: kmod, version: latest, url: https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-26.tar.xz}
    - {name: less, version: latest, url: http://www.greenwoodsoftware.com/less/less-551.tar.gz}
    - {name: lfs, url: http://www.linuxfromscratch.org/lfs/downloads/9.1/lfs-bootscripts-20191031.tar.xz}
    - {name: libcap, version: latest, url: https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.31.tar.xz}
    - {name: libffi, version: latest, url: ftp://sourceware.org/pub/libffi/libffi-3.3.tar.gz}
    - {name: libpipeline, version: latest, url: http://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.2.tar.gz}
    - {name: libtool, version: latest, url: http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz}
    - {name: linux, version: latest, url: https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.5.3.tar.xz}
    - {name: m4, version: latest, url: http://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz}
    - {name: make, version: latest, url: http://ftp.gnu.org/gnu/make/make-4.3.tar.gz}
    - {name: man, version: latest, url: http://download.savannah.gnu.org/releases/man-db/man-db-2.9.0.tar.xz}
    - {name: man, version: latest, url: https://www.kernel.org/pub/linux/docs/man-pages/man-pages-5.05.tar.xz}
    - {name: meson, version: latest, url: https://github.com/mesonbuild/meson/releases/download/0.53.1/meson-0.53.1.tar.gz}
    - {name: mpc, version: latest, url: https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz}
    - {name: mpfr, version: latest, url: http://www.mpfr.org/mpfr-4.0.2/mpfr-4.0.2.tar.xz}
    - {name: ninja, version: latest, url: https://github.com/ninja-build/ninja/archive/v1.10.0/ninja-1.10.0.tar.gz}
    - {name: ncurses, version: latest, url: http://ftp.gnu.org/gnu/ncurses/ncurses-6.2.tar.gz}
    - {name: openssl, version: latest, url: https://www.openssl.org/source/openssl-1.1.1d.tar.gz}
    - {name: patch, version: latest, url: http://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz}
    - {name: perl, version: latest, url: https://www.cpan.org/src/5.0/perl-5.30.1.tar.xz}
    - {name: pkg, version: latest, url: https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz}
    - {name: procps, version: latest, url: https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-3.3.15.tar.xz}
    - {name: psmisc, version: latest, url: https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.2.tar.xz}
    - {name: Python, version: latest, url: https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tar.xz}
    - {name: python, version: latest, url: https://www.python.org/ftp/python/doc/3.8.1/python-3.8.1-docs-html.tar.bz2}
    - {name: readline, version: latest, url: http://ftp.gnu.org/gnu/readline/readline-8.0.tar.gz}
    - {name: sed, version: latest, url: http://ftp.gnu.org/gnu/sed/sed-4.8.tar.xz}
    - {name: shadow, version: latest, url: https://github.com/shadow-maint/shadow/releases/download/4.8.1/shadow-4.8.1.tar.xz}
    - {name: sysklogd, version: latest, url: http://www.infodrom.org/projects/sysklogd/download/sysklogd-1.5.1.tar.gz}
    - {name: systemd, version: latest, url: https://github.com/systemd/systemd/archive/v244/systemd-244.tar.gz}
    - {name: systemd, version: latest, url: http://anduin.linuxfromscratch.org/LFS/systemd-man-pages-244.tar.xz}
    - {name: sysvinit, version: latest, url: http://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.96.tar.xz}
    - {name: tar, version: latest, url: http://ftp.gnu.org/gnu/tar/tar-1.32.tar.xz}
    - {name: tcl8.6.10, version: latest, url: https://downloads.sourceforge.net/tcl/tcl8.6.10-src.tar.gz}
    - {name: texinfo, version: latest, url: http://ftp.gnu.org/gnu/texinfo/texinfo-6.7.tar.xz}
    - {name: tzdata2019c.tar.gz, version: latest, url: https://www.iana.org/time-zones/repository/releases/tzdata2019c.tar.gz}
    - {name: udev, version: latest, url: http://anduin.linuxfromscratch.org/LFS/udev-lfs-20171102.tar.xz}
    - {name: util, version: latest, url: https://www.kernel.org/pub/linux/utils/util-linux/v2.35/util-linux-2.35.1.tar.xz}
    - {name: vim, version: latest, url: http://anduin.linuxfromscratch.org/LFS/vim-8.2.0190.tar.gz}
    - {name: XML, version: latest, url: https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz}
    - {name: xz, version: latest, url: https://tukaani.org/xz/xz-5.2.4.tar.xz}
    - {name: zlib, version: latest, url: https://zlib.net/zlib-1.2.11.tar.xz}
    - {name: zstd, version: latest, url: https://github.com/facebook/zstd/releases/download/v1.4.4/zstd-1.4.4.tar.gz}
    - {name: bash, version: latest, url: http://www.linuxfromscratch.org/patches/lfs/9.1/bash-5.0-upstream_fixes-1.patch}
    - {name: bzip2, version: latest, url: http://www.linuxfromscratch.org/patches/lfs/9.1/bzip2-1.0.8-install_docs-1.patch}
    - {name: coreutils, version: latest, url: http://www.linuxfromscratch.org/patches/lfs/9.1/coreutils-8.31-i18n-1.patch}
    - {name: glibc, version: latest, url: http://www.linuxfromscratch.org/patches/lfs/9.1/glibc-2.31-fhs-1.patch}
    - {name: kbd, version: latest, url: http://www.linuxfromscratch.org/patches/lfs/9.1/kbd-2.2.0-backspace-1.patch}
    - {name: sysvinit, version: latest, url: http://www.linuxfromscratch.org/patches/lfs/9.1/sysvinit-2.96-consolidated-1.patch}
...
