#!/bin/sh
echo "$(date): ${0}" >> /home/seal/startup.log
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	echo "$(date): ${0}...ssh-keygen" >> /home/seal/startup.log
	# Create any missing keys
	/usr/bin/ssh-keygen -A

	echo "$(date): ${0}...sshd" >> /home/seal/startup.log
	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
echo "$(date): ${0} ...almost done" >> /home/seal/startup.log

exit $?

echo "$(date): ${0} ...done" >> /home/seal/startup.log
