#!/bin/sh

echo "$(date): ${0}" > /home/seal/checksys.log
echo "$(which ifconfig)" >> /home/seal/checksys.log
echo "$(ls -lh /)" >> /home/seal/checksys.log
echo "$(ifconfig)" >> /home/seal/checksys.log
echo "$(hostname)" >> /home/seal/checksys.log
echo "$(ps aux)" >> /home/seal/checksys.log
echo "$(iwconfig)" >> /home/seal/checksys.log
echo "$(iw dev wlan0 scan)" >> /home/seal/checksys.log
echo "$(iw dev wlan0 scan | grep SSID)" >> /home/seal/checksys.log

case "$1" in
        start)
                echo "$(date): ${0}...starting" >> /home/seal/checksys.log
                ;;
        stop)
                echo "$(date): ${0}...stopping" >> /home/seal/checksys.log
                ;;
        *)
                echo "Usage: $0 {start|stop}"
                exit 1
esac

echo "$(date): ${0}...done" >> /home/seal/checksys.log
