---
  os-name: "ReswarmOS"
  version: 0.0.1
  codename: "Average Ant"
  board: raspberrypi
  model: raspberry-pi-4
  config: config_v0.1
  root-user:
    username: revenent
    password: reverb
  hostname:
    reckless-reindeer
...
