#!/bin/sh

# fake the fake-hwclock
# https://manpages.debian.org/jessie/fake-hwclock/fake-hwclock.8.en.html

case "$1" in
  start)
	date -s "$(cat /etc/hwclock.data | tr -d '\n')"
	;;
  stop)
	date "+%Y-%m-%d %H:%M:%S" > /etc/hwclock.data
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac
