#!/bin/sh

case "$1" in
	start)
		echo -n "Expanding the root FS: "
		resize2fs /dev/mmcblk0p2 &>/dev/null
		ret=$?
		[ ${ret} -eq 0 ] && echo "done" || echo "failed"
		rm -f /etc/init.d/S23expand-rootfs
		exit ${ret}
		;;
	*)
		echo "Usage: $0 start" >&2
		exit 1
		;;
esac
