#!/bin/sh

# define volume directory
pwdmng="/home/agent"

# check for *.reswarm file in /boot directory
reswmexst=$(ls /boot/ | grep -E ".reswarm" | head -n1)

if [ -z ${reswmexst} ]; then
  echo "no reswarm file found => standalone device running"
  exit 1
else
  echo "found reswarm file: ${reswmexst} => going to launch management agent..."
fi

case "$1" in
  
  start)
    
    echo "lauching Reswarm management agent..."
   
    # login to reswarm registry and pull the management agent
    docker login -u RecordEvolution -p hgwo5f3xd2hf02f3s9fhldj3 registry.reswarm.io
    docker pull registry.reswarm.io/apps/arm_svc_mgmt_agent:latest
    docker pull registry.reswarm.io/apps/arm_svc_app_logs:latest

    # start management-agent container with required volumes and options
    docker run -it --rm --name arm_svg_mgmt_agent \
	       -v ${pwdmng}/config:/home/pirate/config \
	       -v ${pwdmng}/boot:/boot \
	       -v /var/run/docker.sock:/var/run/docker.sock \
	       registry.reswarm.io/apps/arm_svc_mgmt_agent
    ;;
  
  *)
    
    echo "Usage: $0 start"
    exit 1
    ;;

esac

