#
# device-config.yaml
# 
# goes to the rootfs at /etc/device-config.yaml to fix all device-specific 
# information and parameters that have to be employed during FIRST BOOTUP
# and cannot be specified by the ReswarmOS distribution itself
# 
---
  hostname:
    reckless-reindeer
#  users:
#    - {"name":"revenent","passwd":"reverb"}
  wifi:
    ssid: meinefritzbox
    passwd: strenggeheim
...
