#!/bin/sh

# source the configuration parser
. /usr/bin/read-ini.sh

# define filename/path of device configuration
CNFG="/boot/device-config.ini"
WCFG="/etc/hostname"
HCFG="/etc/hosts"

if [ ! -f ${CNFG} ]; then
  echo "device configuration file ${CNFG} is missing" >&2
  exit 1
fi

# extract HOSTNAME from [device] section in device configuration
hstname=$(readini ${CNFG} device HOSTNAME)

# define wpa_supplicant.conf with given credentials
hstnamconf=$(cat << EOF
${hstname}
EOF
)


case "$1" in

  start)

    echo "setting hostname for device.."
    echo "hostname=${hstname}"

    echo "employ hostname"
    hostname ${hstname}

    echo "enter hostname in ${HCFG}"
    hstsln=$(cat /etc/hosts | grep "^127.0.1.1 *.*")
    sed -i "s/${hstsln}/127.0.1.1\t${hstname}/g" /etc/hosts

    echo "writing to ${WCFG}"
    echo "${hstnamconf}" > ${WCFG}

    rm -vf $0
    ;;

  *)

    echo "Usage: $0 start"
    exit 1
    ;;

esac

