#!/bin/sh

# source the configuration parser
. /usr/bin/read-ini.sh

# define filename/path of device configuration
CNFG="/boot/device-config.ini"
WCFG="/etc/wpa_supplicant.conf"

if [ ! -f ${CNFG} ]; then
  echo "device configuration file ${CNFG} is missing" >&2
  exit 1
fi

# extract [wifi] section and access credentials device configuration
ssid=$(read-config-ini ${CNFG} wifi SSID)
passwd=$(read-config-ini ${CNFG} wifi PASSWD)

# define wpa_supplicant.conf with given credentials
wpaconf=$(cat << EOF
ctrl_interface=/var/run/wpa_supplicant
ap_scan=1

network={
  ssid="${ssid}"
  psk="${passwd}"
}
EOF
)


case "$1" in

  start)

    echo "setting up wpa_supplicant.conf for immediate network access..."
    
    echo "writing to ${WCFG}"
    echo "${wpaconf}" > ${WCFG}
    
    rm -vf $0
    ;;

  *)

    echo "Usage: $0 start"
    exit 1
    ;;

esac

