#!/bin/sh

# - https://unix.stackexchange.com/questions/79909/how-to-add-a-unix-linux-user-in-a-bash-script
# - https://askubuntu.com/questions/94060/run-adduser-non-interactively

source /usr/bin/read-ini.sh

# define filename/path of device configuration
CNFG="/boot/device-config.ini"

if [ ! -f ${CNFG} ]; then
  echo "device configuration file ${CNFG} is missing" >&2
  exit 1
fi

# extract [user] section and access credentials device configuration
usrname=$(read-config-ini ${CNFG} user USERNAME)
passwd=$(read-config-ini ${CNFG} user PASSWD)
homedir=$(read-config-ini ${CNFG} user HOME)

if [ -z ${usrname} ]; then
  echo "username is empty: invalid user configuration" >&2
  exit 1
fi
if [ -z ${passwd} ]; then
  echo "password is empty: invalid user configuration" >&2
  exit 1
fi
if [ -z ${usrname} ]; then
  echo "no home directory given: invalid user configuration" >&2
  exit 1
fi

case "$1" in
  
  start)
    
    echo "adding required user... "
    echo -n "${usersection}"

    # create user's home directory
    mkdir -pv ${homedir}

    # keep in mind: we're using Busybox's adduser!!
    adduser -h ${homedir} -g "" -s /bin/bash -G sudo ${usrname} << EOF
${passwd}
${passwd}
EOF
   
    # remove script itself 
    rm -vf $0
    ;;
  
  *)
    
    echo "Usage: $0 start"
    exit 1
    ;;

esac
