#!/bin/sh

source /usr/bin/read-ini.sh

case "$1" in
  
  start)
    
    echo "lauching Reswarm management agent..."
    
    # docker run --detach management-agent:latest TODO
    ;;
  
  *)
    
    echo "Usage: $0 start"
    exit 1
    ;;

esac

