#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
  ssh:
    allow-pw: true
    install-server: false
  storage:
    config:
      - ptable: gpt
        wipe: superblock-recursive
        preserve: false
        name: ""
        grub_device: true
        type: disk
        id: disk-sda
      - device: disk-sda
        size: 1048576
        flag: bios_grub
        number: 1
        preserve: false
        grub_device: false
        type: partition
        id: partition-0
      - device: disk-sda
        size: 40%
        wipe: superblock
        flag: ""
        number: 2
        preserve: false
        grub_device: false
        type: partition
        id: partition-1
      - fstype: ext4
        volume: partition-1
        preserve: false
        type: format
        id: format-0
      - path: /
        device: format-0
        type: mount
        id: mount-0
      - device: disk-sda
        size: 512M
        wipe: superblock
        flag: ""
        number: 3
        preserve: false
        grub_device: false
        type: partition
        id: partition-2
      - fstype: ext4
        volume: partition-2
        preserve: false
        type: format
        id: format-1
      - path: /boot
        device: format-1
        type: mount
        id: mount-1
      - device: disk-sda
        size: -1
        wipe: superblock
        flag: ""
        number: 4
        preserve: false
        grub_device: false
        type: partition
        id: partition-3
      - fstype: ext4
        volume: partition-3
        preserve: false
        type: format
        id: format-2
      - path: /apps
        device: format-2
        type: mount
        id: mount-2
  late-commands:
    - sed -i 's/ENABLED=1/ENABLED=0/g' /target/etc/default/motd-news
    - sed -i 's/^session    optional     pam_motd.so/#session    optional     pam_motd.so/g' /target/etc/pam.d/sshd
    - sed -i 's/^session    optional   pam_motd.so/#session    optional   pam_motd.so/g' /target/etc/pam.d/login
    - curtin in-target --target=/target -- passwd -q -u root
    - sed -i 's|^root:.:|root:$6$3b873df474b55246$GIpSsujar7ihMzG8urUKpzF9/2yZJhR.msyFRa5ouGXOKRCVszsc4aBcE2yi3IuFVxtAGwrPKin2WAzK3qOtB.:|' /target/etc/shadow
    - cp /boot/*.reswarm /target/boot
  user-data:
    disable_root: false