#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
  ssh:
    allow-pw: true
    install-server: false
  storage:
    config:
        - ptable: gpt
          wipe: superblock-recursive
          preserve: false
          name: ''
          grub_device: false
          type: disk
          id: disk-sda
        - device: disk-sda
          size: 512M
          wipe: superblock
          flag: boot
          number: 1
          preserve: false
          grub_device: true
          type: partition
          id: partition-0
        - fstype: fat32
          volume: partition-0
          preserve: false
          type: format
          id: format-0
        - device: disk-sda
          size: 5G
          wipe: superblock
          flag: ''
          number: 2
          preserve: false
          grub_device: false
          type: partition
          id: partition-1
        - fstype: ext4
          volume: partition-1
          preserve: false
          type: format
          id: format-1
        - path: /
          device: format-1
          type: mount
          id: mount-1
        - device: disk-sda
          size: 5G
          wipe: superblock
          flag: ''
          number: 3
          preserve: false
          grub_device: false
          type: partition
          id: partition-2
        - fstype: ext4
          volume: partition-2
          preserve: false
          type: format
          id: format-2
        - device: disk-sda
          size: 512M
          wipe: superblock
          flag: ''
          number: 4
          preserve: false
          grub_device: false
          type: partition
          id: partition-3
        - fstype: ext4
          volume: partition-3
          preserve: false
          type: format
          id: format-3
        - path: /boot
          device: format-3
          type: mount
          id: mount-3
        - device: disk-sda
          size: -1
          wipe: superblock
          flag: ''
          number: 5
          preserve: false
          grub_device: false
          type: partition
          id: partition-4
        - fstype: ext4
          volume: partition-4
          preserve: false
          type: format
          id: format-4
        - path: /apps
          device: format-4
          type: mount
          id: mount-4
        - path: /boot/efi
          device: format-0
          type: mount
          id: mount-0
  late-commands:
    - curtin in-target --target=/target -- apt-get --purge -y --quiet=2 remove apport bcache-tools btrfs-progs byobu cloud-guest-utils cloud-initramfs-copymods cloud-initramfs-dyn-netconf friendly-recovery fwupd landscape-common lxd-agent-loader ntfs-3g open-vm-tools plymouth plymouth-theme-ubuntu-text popularity-contest screen snapd sosreport tmux os-prober telnet || true
    - curtin in-target --target=/target -- apt-get --purge -y --quiet=2 autoremove || true
    - curtin in-target --target=/target -- apt-get clean || true
    - rm -rf /target/root/snap || true
    - rm -rf /target/snap || true
    - rm -rf /target/var/lib/snapd || true
    - rm -rf /target/var/snap || true
    - sed -i 's/ENABLED=1/ENABLED=0/g' /target/etc/default/motd-news
    - sed -i 's/^session    optional     pam_motd.so/#session    optional     pam_motd.so/g' /target/etc/pam.d/sshd
    - sed -i 's/^session    optional   pam_motd.so/#session    optional   pam_motd.so/g' /target/etc/pam.d/login
    - curtin in-target --target=/target -- passwd -q -u root
    - sed -i 's|^root:.:|root:$6$3b873df474b55246$GIpSsujar7ihMzG8urUKpzF9/2yZJhR.msyFRa5ouGXOKRCVszsc4aBcE2yi3IuFVxtAGwrPKin2WAzK3qOtB.:|' /target/etc/shadow
    - cp /cdrom/boot/*.reswarm /target/boot || true
    - cp /target/etc/config/* /target/etc
    - /target/usr/sbin/update-device-names.sh
    - curtin in-target --target=/target -- update-grub
  user-data:
    disable_root: false