---
description: "Filesystem Hierarchy Standard:
              list of directories to be found in '/' of the root filesystem"
urlreference: "https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s02.html"
root:
  "bin":
    description: "Essential command binaries"
    requirements:
      - "there must be no subdirectories"
      - "command or symbolic links to commands": ["cat","chgrp","chmod",
        "chown","cp","date","dd","df","dmesg","echo","false","hostname",
        "kill","ln","login","ls","mkdir","mknod","more","mount","mv","ps",
        "pwd","rm","rmdir","sed","sh","stty","su","sync","true","umount",
        "uname"]
    permissions: ""
    subdirectory:
  "boot":
    description: "Static files of the boot loader"
    requirements:
      - "data that is used before the kernel begins executing user-mode programs"
      - "operating system kernel must be located in either / or /boot"
    permissions: ""
    subdirectory:
  "dev":
    description: "Device files"
    requirements:
    permissions: ""
    subdirectory:
  "etc":
    description: "Host-specific system configuration"
    requirements:
      - "No binaries may be located under /etc."
      - "files, or symbolic links to files, must (evtl.) be in /etc": ["csh.login",
          "exports","fstab","ftpusers","gateways","gettydefs","group","host.conf",
          "hosts","hosts.allow","hosts.deny","hosts.equiv","hosts.lpd","inetd.conf",
          "inittab","issue","ld.so.conf","motd","mtab","mtools.conf","networks",
          "passwd","printcap","profile","protocols","resolv.conf","rpc","securetty",
          "services","shells","syslog.conf"]
    permissions: ""
    subdirectory:
      "opt":
        "description":
        "requirements":
        "permissions":
        "subdirectory":
  "home":
    description: "User home directories (optional)"
    permissions: ""
    subdirectory:
  "lib":
    description: "Essential shared libraries and kernel modules"
    requirements:
      - "one of the following filename patterns are required":
        - "libc.so.*	The dynamically-linked C library (optional)"
        - "ld*	The execution time linker/loader (optional)"
    permissions: ""
    subdirectory:
      "modules":
        "description":
        "requirements":
  "media":
    description: "Mount point for removable media"
    permissions: ""
    subdirectory:
  "mnt":
    description: "Mount point for mounting a filesystem temporarily"
    requirements: "directory must not be used by installation programs"
    permissions: ""
    subdirectory:
  "opt":
    description: "Add-on application software packages"
    requirements:
      - "directories reserved for local system administrator use: /opt/bin,/opt/doc,/opt/include,/opt/info,/opt/lib,/opt/man"
      - "programs to be invoked by users must be located in the directory hierarchy: /opt/<package>/bin, /opt/<provider>"
      - "UNIX manual pages of any packages must be located in: /opt/<package>/share/man, /opt/<provider> hierarchy"
    permissions: ""
    subdirectory:
  "run":
    description: "Data relevant to running processes"
    requirements:
      - "Files under this directory must be cleared at the beginning of the boot process"
      - "Process identifier (PID) files, which were originally placed in /etc, must be placed in /run"
      - "The naming convention for PID files is <program-name>.pid"
    permissions: ""
    subdirectory:
  "sbin":
    description: "Essential system binaries"
    requirements:
      - "There must be no subdirectories in /sbin"
      - "following commands, or symbolic links to commands, are required in /sbin: shutdown"
      - "following files, or symbolic links to files, must be in /sbin if the corresponding subsystem is installed: fastboot, fasthalt, fdisk, fsck, fsck.*, getty, halt, ifconfig, init, mkfs, mkfs.*, mkswap, reboot, route, swapon, swapoff, update"
    permissions: ""
    subdirectory:
  "srv":
    description: "Data for services provided by this system"
    requirements:
    permissions: ""
    subdirectory:
  "tmp":
    description: "Temporary files"
    requirements:
      - "The /tmp directory must be made available for programs that require temporary files"
      - "Programs must not assume that any files or directories in /tmp are preserved between invocations of the program"
    permissions: "1777"
    subdirectory:
  "usr":
    description: "Secondary hierarchy"
    details: "second major section of the filesystem"
    requirements:
      - "Directory is shareable, read-only data"
      - "Directory should be shareable between various FHS-compliant hosts and must not be written to"
    permissions: ""
    subdirectory:
      "bin":
        requirements:
          - "There must be no subdirectories"
      "include":
        description:
        details: "This is where all of the system's general-use include files for the C programming language should be placed"
      "lib":
        description: "includes object files and libraries"
        requirements:
          - "Applications may use a single subdirectory under /usr/lib"
      "local":
        description:
        details: "The /usr/local hierarchy is for use by the system administrator when installing software locally"
        requirements:
          - "It needs to be safe from being overwritten when the system software is updated"
        permissions: ""
        subdirectory:
          "bin":
            "description":
          "etc":
            "description":
          "games":
            "description":
          "include":
            "description":
          "lib":
            "description":
          "man":
            "description":
          "sbin":
            "description":
          "share":
            "description":
          "src":
            "description":
      "sbin":
        requirements:
          - "There must be no subdirectories"
      "share":
        description:
        details: "The /usr/share hierarchy is for all read-only architecture independent data files"
        permissions: ""
        subdirectory:
          "man":
            description:
            details: "Contains manual information for commands and data under the / and /usr filesystems"
            subdirectory:
              "man1":
                description: "User programs (optional)"
              "man2":
                description: "System calls (optional)"
              "man3":
                description: "Library calls (optional)"
              "man4":
                description: "Special files (optional)"
              "man5":
                description: "File formats (optional)"
              "man6":
                description: "Games (optional)"
              "man7":
                description: "Miscellaneous (optional)"
              "man8":
                description: "System administration (optional)"
      "misc":
        description: "Contains miscellaneous architecture-independent files which don't require a separate subdirectory under /usr/share"
        subdirectory:
  "var":
    description: "Variable data"
    details: "/var contains variable data files. This includes spool directories and files, administrative and logging data, and transient and temporary files"
    requirements: "Several directories must not be used arbitrarily by some new application: backups, cron, msgs, preserve"
    permissions: ""
    subdirectory:
      "cache":
        description: "Application cache data"
        details: "intended for cached data from applications"
      "lib":
          description: "Variable state information"
          details: "This hierarchy holds state information pertaining to an application or the system"
          permissions: ""
          subdirectory:
            "misc":
              "description":
      "local":
          description: "Variable data for /usr/local"
      "lock":
          description: "Lock files"
          details: "Lock files should be stored within the /var/lock directory structure"
          permissions: ""
      "log":
          description: "Log files and directories"
          details: "This directory contains miscellaneous log files. Most logs must be written to this directory or an appropriate subdirectory"
          permissions: ""
      "opt":
          description: "Variable data for /opt"
          details: "Variable data of the packages in /opt must be installed in /var/opt/<subdir>, where <subdir> is the name of the subtree in /opt"
          permissions: ""
      "run":
          description: "Data relevant to running processes"
      "spool":
          description: "Application spool data"
          details: "/var/spool contains data which is awaiting some kind of later processing"
          permissions: ""
      "tmp":
          description: "Temporary files preserved between system reboots"
          details: "The /var/tmp directory is made available for programs that require temporary files or directories that are preserved between system reboots"
          requirements: "Files and directories located in /var/tmp must not be deleted when the system is booted"
          permissions: "1777"
...
