#!/bin/sh

# define filename/path of (reswarm) configuration
CNFG="/boot/device-config.ini"

# define volume directory
# pwdmng="/home/agent"

# check for *.reswarm file in /boot directory
reswmexst=$(ls /boot/ | grep -E ".reswarm" | head -n1)

if [ -z ${reswmexst} ]; then
  echo "no reswarm file found => going to set up device according to device-config.ini"
  exit 1
else
  echo "found reswarm file: ${reswmexst}"
fi


case "$1" in

  start)

    echo "parsing and extracting *.reswarm device configuration..."
  
    # preliminary solution! => mount directory and config files according to weird 
    # requirements of wamp_management.py
    #mkdir -pv ${pwdmng}/config
    #mkdir -pv ${pwdmng}/boot
    
    # apparently the management-agent expects boot/config.txt and boot/cmdline.txt as well
    #cp -v /boot/config.txt ${pwdmng}/boot/
    #cp -v /boot/cmdline.txt ${pwdmng}/boot/
    
    # find and parse *.reswarm configuration and write separate configuration files to appropriate locations
    python3 /usr/bin/parse-config.py /boot/${reswmexst} ${CNFG}
    
    rm -vf $0
    ;;

  *)

    echo "Usage: $0 start"
    exit 1
    ;;

esac

