---
  # ("BIOS") configuration file
  # https://www.raspberrypi.org/documentation/configuration/config-txt/
  config.txt:
    memory:
      gpu_mem:
    codec:
    display:
      hdmi_safe: 1
      hdmi_force_hotplug:
      config_hdmi_boost:
      hdmi_group: 1
      hdmi_mode: 1
      hdmi_force_mode:
      test_mode:
    audio:
    camera:
    boot:
      cmdline: cmdline.txt
      kernel:
      arm_64bit:
      kernel_address:
      boot_delay:
    device:
    gpio:
    overclocking:
    filters:
    misc:
      # https://www.raspberrypi.org/documentation/configuration/uart.md
      enable_uart: 1
  # Kernel command line
  # https://www.raspberrypi.org/documentation/configuration/cmdline-txt.md
  cmdline.txt:
    console: ["serial0,115200","tty1"]
    root:
    rootfstype:
    splash:

...
