#!/bin/bash
# generated by 'image/prepare_image.py'

source log/logging.sh

logging_message "creating image file"

# create image file of appropriate total size
dd if=/dev/zero of=/home/mario/reswarm-os/ReswarmOS_0.1.img bs=1M count=751

# check image path and size
ls -lh /home/mario/reswarm-os/ReswarmOS_0.1.img

logging_message "prepare loopback device"

# find next unused loopback device
devName=$(losetup -f) 

# set up loopback device with image file
losetup -fP /home/mario/reswarm-os/ReswarmOS_0.1.img

# check new loopback device
losetup -a 
losetup -l ${devName}

logging_message "set disk label"

# create disk label
parted ${devName} --script mklabel msdos 

logging_message "create partitions"

# create partitions and employ required filesystems
parted ${devName} --script mkpart primary vfat 1048577B 210763776B
mkfs.vfat ${devName}p1
parted ${devName} --script mkpart primary ext4 210763777B 787480576B
mkfs.ext4 ${devName}p2

logging_message "check partitions"

# check partitions
parted ${devName} print

